package utils;

public class Queries {

	public final static String ADD_EVENT = " INSERT INTO EVENTS(EVENT_ID,EVENT_NAME,EVENT_DESC,VENUE) VALUES (?,?,?,?);";
	public final static String ADD_PARTICIPANT = "INSERT INTO PARTICIPANTS(P_ID,P_NAME,P_MAIL,P_PHONE,P_PASSWORD) VALUES(?,?,?,?,?)";
	public final static String VIEW_EVENT= "SELECT EVENT_ID,EVENT_NAME,EVENT_DESC,VENUE FROM EVENTS WHERE IS_DELETED = 0;";
	public final static String VIEW_PARTICIPANT = "SELECT P_ID,P_NAME,P_MAIL,P_PHONE,P_PASSWORD FROM PARTICIPANTS WHERE  IS_DELETED = 0;";
	public final static String VIEW_PARTICIPANT_BY_ID = "SELECT P_ID,P_NAME,P_MAIL,P_PHONE,P_PASSWORD FROM PARTICIPANTS WHERE  IS_DELETED = 0 AND P_NAME = ?;";
	public final static String DETAILS = "SELECT E.EVENT_ID,P.P_ID FROM EVENTS E LEFT JOIN PARTICIPANTS P ON E.IS_DELETED = P.IS_DELETED WHERE E.IS_DELETED = 0 AND P.IS_DELETED = 0 GROUP BY  E.EVENT_ID,P.P_ID;";
	public final static String VIEW_REGISTERS = "SELECT E.EVENT_ID,E.EVENT_NAME,E.EVENT_DESC,STRING_AGG(R.P_ID,',') AS P_IDS FROM EVENTS E LEFT JOIN	REGISTERS R ON E.EVENT_ID = R.EVENT_ID GROUP BY E.EVENT_ID,	E.EVENT_NAME,E.EVENT_DESC ORDER BY 	E.EVENT_ID;";
	public final static String DELETE_EVENT = "UPDATE EVENTS SET IS_DELETED = 1 WHERE EVENT_ID = ? ;";
	public final static String DELETE_PARTICIPANT = "UPDATE PARTICIPANTS SET IS_DELETED = 1 WHERE P_ID = ?;";
	public final static String REGISTER_FOR_EVENT = " INSERT INTO REGISTERS VALUES  (?, ?, ?);";
//	private final static String UPDATE_EVENT = "UPDATE EVENT SET COLUMN WHERE EVENT_ID = ?";
//	private final static String UPDATE_PARTICIPANT = "UPDATE PARTICIPANTS SET COLUMN WHERE P_ID = ?";
	
	
}

